src/Entity/Episode.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EpisodeRepository")
 */
class Episode
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $season_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\Column(type="text")
     */
    private $synopsys;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Season", inversedBy="episodes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $season;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSeasonId(): ?int
    {
        return $this->season_id;
    }

    public function setSeasonId(int $season_id): self
    {
        $this->season_id = $season_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getSynopsys(): ?string
    {
        return $this->synopsys;
    }

    public function setSynopsys(string $synopsys): self
    {
        $this->synopsys = $synopsys;

        return $this;
    }

    public function getSeason(): ?Season
    {
        return $this->season;
    }

    public function setSeason(?Season $season): self
    {
        $this->season = $season;

        return $this;
    }
}

src/Form/EpisodeType.php
<?php

namespace App\Form;

use App\Entity\Episode;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EpisodeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('number')
            ->add('synopsys')
            ->add('season', null, ['choice_label' => 'number'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Episode::class,
        ]);
    }
}

src/Controller/EpisodeController.php
<?php

namespace App\Controller;

use App\Entity\Episode;
use App\Form\EpisodeType;
use App\Repository\EpisodeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/episode")
 */
class EpisodeController extends AbstractController
{
    /**
     * @Route("/", name="episode_index", methods={"GET"})
     */
    public function index(EpisodeRepository $episodeRepository): Response
    {
        return $this->render('episode/index.html.twig', [
            'episodes' => $episodeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="episode_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $episode = new Episode();
        $form = $this->createForm(EpisodeType::class, $episode);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($episode);
            $entityManager->flush();

            return $this->redirectToRoute('episode_index');
        }

        return $this->render('episode/new.html.twig', [
            'episode' => $episode,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="episode_show", methods={"GET"})
     */
    public function show(Episode $episode): Response
    {
        return $this->render('episode/show.html.twig', [
            'episode' => $episode,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="episode_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Episode $episode): Response
    {
        $form = $this->createForm(EpisodeType::class, $episode);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('episode_index');
        }

        return $this->render('episode/edit.html.twig', [
            'episode' => $episode,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="episode_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Episode $episode): Response
    {
        if ($this->isCsrfTokenValid('delete'.$episode->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($episode);
            $entityManager->flush();
        }

        return $this->redirectToRoute('episode_index');
    }
}

templates/episode/_delete_form.html.twig
<form method="post" action="{{ path('episode_delete', {'id': episode.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ episode.id) }}">
    <button class="btn">Delete</button>
</form>

templates/episode/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/episode/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Episode{% endblock %}

{% block body %}
    <h1>Edit Episode</h1>

    {{ include('episode/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('episode_index') }}">back to list</a>

    {{ include('episode/_delete_form.html.twig') }}
{% endblock %}

templates/episode/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Episode index{% endblock %}

{% block body %}
    <h1>Episode index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Season_id</th>
                <th>Title</th>
                <th>Number</th>
                <th>Synopsys</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for episode in episodes %}
            <tr>
                <td>{{ episode.id }}</td>
                <td>{{ episode.seasonId }}</td>
                <td>{{ episode.title }}</td>
                <td>{{ episode.number }}</td>
                <td>{{ episode.synopsys }}</td>
                <td>
                    <a href="{{ path('episode_show', {'id': episode.id}) }}">show</a>
                    <a href="{{ path('episode_edit', {'id': episode.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('episode_new') }}">Create new</a>
{% endblock %}

templates/episode/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Episode{% endblock %}

{% block body %}
    <h1>Create new Episode</h1>

    {{ include('episode/_form.html.twig') }}

    <a href="{{ path('episode_index') }}">back to list</a>
{% endblock %}

templates/episode/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Episode{% endblock %}

{% block body %}
    <h1>Episode</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ episode.id }}</td>
            </tr>
            <tr>
                <th>Season_id</th>
                <td>{{ episode.seasonId }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ episode.title }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ episode.number }}</td>
            </tr>
            <tr>
                <th>Synopsys</th>
                <td>{{ episode.synopsys }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('episode_index') }}">back to list</a>

    <a href="{{ path('episode_edit', {'id': episode.id}) }}">edit</a>

    {{ include('episode/_delete_form.html.twig') }}
{% endblock %}